### ISSUE TITLE
peek(>0) throws exception when reaching EOF

### ISSUE THREAD

**Issue by Cydhra** [compilerpraktikum/compiler#75]
Ich dachte wir hatten sichergestellt, dass der Compiler nicht explodiert, wenn ein ungünstiges EOF erreicht wird.

Aber ein lookahead über mehrere Zeichen (an einer new-array-expression) führt zu einer unhandled exception:

Eingabe:
```Java
class A {
    public static void main(String[] args) {
        int a = new int
```

```
Internal error: tried to peek past the end of the sequence
java.lang.IllegalStateException: tried to peek past the end of the sequence
	at edu.kit.compiler.parser.LookaheadBuffer.peek(LookaheadBuffer.kt:43)
	at edu.kit.compiler.parser.AbstractParser.peek(AbstractParser.kt:45)
	at edu.kit.compiler.parser.AbstractParser.peek$default(AbstractParser.kt:45)
	at edu.kit.compiler.parser.Parser.parseUnaryExpression-7yDSdB4(Parser.kt:366)
	at edu.kit.compiler.parser.Parser.parseExpression-Qkhz27U$compiler(Parser.kt:395)
	at edu.kit.compiler.parser.Parser.parseExpression-Qkhz27U$compiler$default(Parser.kt:391)
	at edu.kit.compiler.parser.Parser.parseNewArrayExpression-7yDSdB4(Parser.kt:201)
	at edu.kit.compiler.parser.Parser.parseNewObjectArrayExpression-7yDSdB4(Parser.kt:136)
	at edu.kit.compiler.parser.Parser.parsePrimaryExpression-7yDSdB4(Parser.kt:106)
	at edu.kit.compiler.parser.Parser.parsePostfixExpression-7yDSdB4(Parser.kt:263)
	at edu.kit.compiler.parser.Parser.parseUnaryExpression-7yDSdB4(Parser.kt:387)
	at edu.kit.compiler.parser.Parser.parseExpression-Qkhz27U$compiler(Parser.kt:395)
	at edu.kit.compiler.parser.Parser.parseExpression-Qkhz27U$compiler$default(Parser.kt:391)
	at edu.kit.compiler.parser.Parser.parseLocalVariableDeclarationStatement-7yDSdB4(Parser.kt:1103)
	at edu.kit.compiler.parser.Parser.parseBlockStatement-7yDSdB4(Parser.kt:865)
	at edu.kit.compiler.parser.Parser.parseBlockStatements(Parser.kt:841)
	at edu.kit.compiler.parser.Parser.parseBlock-7yDSdB4$compiler(Parser.kt:813)
	at edu.kit.compiler.parser.Parser.parseMainMethod-7yDSdB4(Parser.kt:659)
	at edu.kit.compiler.parser.Parser.parseClassMember-7yDSdB4(Parser.kt:536)
	at edu.kit.compiler.parser.Parser.parseClassMembers-7yDSdB4(Parser.kt:486)
	at edu.kit.compiler.parser.Parser.parseClassDeclarations-7yDSdB4$compiler(Parser.kt:460)
	at edu.kit.compiler.parser.Parser.parse(Parser.kt:38)
	at edu.kit.compiler.Compiler.compile(Compiler.kt:82)
	at edu.kit.compiler.Cli.run(Main.kt:26)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
	at edu.kit.compiler.MainKt.main(Main.kt:30)

Process finished with exit code 127
```

**Comment by Cydhra** [comment]
@iTob191 sollten wir das im Parser abfangen oder peek() einfach für jeden illegalen Lookahead EOF zurückgeben lassen? Jetzt wo es nicht mehr asynchron ist, sollte das doch gehen? (Insbesondere soll der Stream trotzdem enden, wir geben es einfach in peek() künstlich zurück)

**Comment by Cydhra** [comment]
Die Eingabe
```Java
class A {
    public static void main(String[] args) {
        int a = new int[
```
erzeugt ebenfalls einen Crash, aber an einer anderen Stelle, weil dort ebenfalls ein illegaler Lookahead geschieht:

```
Internal error: tried to peek past the end of the sequence
java.lang.IllegalStateException: tried to peek past the end of the sequence
	at edu.kit.compiler.parser.LookaheadBuffer.peek(LookaheadBuffer.kt:43)
	at edu.kit.compiler.parser.AbstractParser.peek(AbstractParser.kt:45)
	at edu.kit.compiler.parser.Parser.parseNewArrayExpressionTypeArrayRecurse-Qkhz27U(Parser.kt:221)
	at edu.kit.compiler.parser.Parser.parseNewArrayExpression-7yDSdB4(Parser.kt:208)
	at edu.kit.compiler.parser.Parser.parseNewObjectArrayExpression-7yDSdB4(Parser.kt:136)
	at edu.kit.compiler.parser.Parser.parsePrimaryExpression-7yDSdB4(Parser.kt:106)
	at edu.kit.compiler.parser.Parser.parsePostfixExpression-7yDSdB4(Parser.kt:263)
	at edu.kit.compiler.parser.Parser.parseUnaryExpression-7yDSdB4(Parser.kt:387)
	at edu.kit.compiler.parser.Parser.parseExpression-Qkhz27U$compiler(Parser.kt:395)
	at edu.kit.compiler.parser.Parser.parseExpression-Qkhz27U$compiler$default(Parser.kt:391)
	at edu.kit.compiler.parser.Parser.parseLocalVariableDeclarationStatement-7yDSdB4(Parser.kt:1103)
	at edu.kit.compiler.parser.Parser.parseBlockStatement-7yDSdB4(Parser.kt:865)
	at edu.kit.compiler.parser.Parser.parseBlockStatements(Parser.kt:841)
	at edu.kit.compiler.parser.Parser.parseBlock-7yDSdB4$compiler(Parser.kt:813)
	at edu.kit.compiler.parser.Parser.parseMainMethod-7yDSdB4(Parser.kt:659)
	at edu.kit.compiler.parser.Parser.parseClassMember-7yDSdB4(Parser.kt:536)
	at edu.kit.compiler.parser.Parser.parseClassMembers-7yDSdB4(Parser.kt:486)
	at edu.kit.compiler.parser.Parser.parseClassDeclarations-7yDSdB4$compiler(Parser.kt:460)
	at edu.kit.compiler.parser.Parser.parse(Parser.kt:38)
	at edu.kit.compiler.Compiler.compile(Compiler.kt:82)
	at edu.kit.compiler.Cli.run(Main.kt:26)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
	at edu.kit.compiler.MainKt.main(Main.kt:30)

Process finished with exit code 127
```

**Comment by iTob191** [comment]
> @iTob191 sollten wir das im Parser abfangen oder peek() einfach für jeden illegalen Lookahead EOF zurückgeben lassen? Jetzt wo es nicht mehr asynchron ist, sollte das doch gehen? (Insbesondere soll der Stream trotzdem enden, wir geben es einfach in peek() künstlich zurück)

Naja, das `peek()` was da verwendet wird, ist ausm Lookahead-Buffer, der selbst einfach nur ne token sequence kriegt. Also wenn man das da einbaut, dann so, das er einfach das letzte Zeichen wiederholt, falls es nicht weitergeht. Bin ich allerdings kein allzu großer Fan von. Würde es abhängig davon machen, wie viel Aufwand das ist, das im Parser zu ersetzen.

**Comment by iTob191** [comment]
👍
